### ISSUE TITLE
Any way to import history data from GitHub

### ISSUE THREAD

**Issue by samuel-ye** [keen/github-analytics#4]
It seems that new GitHub event data stream to Keen.io thru webhooks, but any solution to import existing data (like comments/issues/...) to Keen.io project?

Thanks in advance

**Comment by dustinlarimer** [comment]
@samuel-ye apologies, but no I'm afraid this is not possible. If you reach out to Github support they _might_ be able to re-run past activity through the webhooks, but it's a long-shot.. I'm not sure if they even retain history long enough to do this.
